apiVersion: v1
kind: Service
metadata:
  name: nginx-web
  labels:
    app: nginx-web
    run: nginx-web
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer or use the existing NodePort
  type: LoadBalancer
  ports:
    # the port that this service should serve on
    - name: web
      port: 8280
      targetPort: web
  selector:
    app: nginx-web
