#!/bin/bash

# Welcome Message
echo -e ""
echo -e "\e[1;32mWelcome! Today is $(date +'%A, %B %d, %Y').\e[0m"
echo -e "\e[1;33m--------------------------------------------------------------------------------------------------------\e[0m"
# Random Quote of the Day
QUOTES=(
    "The only way to do great work is to love what you do. – Steve Jobs"
    "Success is not the key to happiness. Happiness is the key to success. – Albert Schweitzer"
    "What we do in life echoes an eternity. - Maximus"
    "Do what you can, with what you have, where you are. – Theodore Roosevelt"
    "Believe you can and you're halfway there. – Theodore Roosevelt"
    "If you will it, it is no dream. - Theodor Herzl"
    "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt"
)
RANDOM_QUOTE=${QUOTES[$RANDOM % ${#QUOTES[@]}]}
echo -e "\e[1;34mQuote of the Day: \"$RANDOM_QUOTE\"\e[0m"

# System Stats
# echo -e "\e[1;33m--- System Information ---\e[0m"

# Uptime
# UPTIME=$(uptime -p)
# echo -e "\e[1;36mUptime:\e[0m $UPTIME"

# CPU Usage
# CPU_LOAD=$(top -bn1 | grep "load average" | awk '{print $10 $11 $12}' | sed 's/,//g')
# echo -e "\e[1;36mCPU Load:\e[0m $CPU_LOAD"

# Memory Usage
# MEMORY=$(free -h | grep Mem | awk '{print $3 "/" $2}')
# echo -e "\e[1;36mMemory Usage:\e[0m $MEMORY"

# Disk Usage
# DISK_USAGE=$(df -h / | tail -1 | awk '{print $3 "/" $2 " (" $5 " used)"}')
# echo -e "\e[1;36mDisk Usage:\e[0m $DISK_USAGE"

# Network Information
# IP_ADDRESS=$(hostname -I | awk '{print $1}')
# echo -e "\e[1;36mIP Address:\e[0m $IP_ADDRESS"

# Number of Users Logged In
# LOGGED_IN_USERS=$(who | wc -l)
# echo -e "\e[1;36mLogged-In Users:\e[0m $LOGGED_IN_USERS"
echo -e "\e[1;33m--------------------------------------------------------------------------------------------------------\e[0m"
echo -e "Quick Setup!"
echo -e "\e[1;36m  Type (quick-setup) to setup env vars and install resources!\e[0m"
echo -e "\e[1;36m  Tip- After modifying env vars in the menu, exit (x) then type (renv) to refresh/source or (denv) to temp reset/unsource. \e[0m"
echo -e "\e[1;36m  Tip- Type (motd) to display this message again. \e[0m"
echo -e ""

